// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: whisperingtime.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	mi := &file_whisperingtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{0}
}

func (x *BasicResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *BasicResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_whisperingtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{1}
}

// Theme models
type ThemeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeSummary) Reset() {
	*x = ThemeSummary{}
	mi := &file_whisperingtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeSummary) ProtoMessage() {}

func (x *ThemeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeSummary.ProtoReflect.Descriptor instead.
func (*ThemeSummary) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{2}
}

func (x *ThemeSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThemeSummary) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

type PermissionEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedKey  []byte                 `protobuf:"bytes,1,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionEnvelope) Reset() {
	*x = PermissionEnvelope{}
	mi := &file_whisperingtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionEnvelope) ProtoMessage() {}

func (x *PermissionEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionEnvelope.ProtoReflect.Descriptor instead.
func (*PermissionEnvelope) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionEnvelope) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

func (x *PermissionEnvelope) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GroupConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Levels         []bool                 `protobuf:"varint,3,rep,packed,name=levels,proto3" json:"levels,omitempty"`
	ViewType       int32                  `protobuf:"varint,4,opt,name=view_type,json=viewType,proto3" json:"view_type,omitempty"`
	SortType       int32                  `protobuf:"varint,5,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"`
	AutoFreezeDays int32                  `protobuf:"varint,6,opt,name=auto_freeze_days,json=autoFreezeDays,proto3" json:"auto_freeze_days,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupConfig) Reset() {
	*x = GroupConfig{}
	mi := &file_whisperingtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupConfig) ProtoMessage() {}

func (x *GroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupConfig.ProtoReflect.Descriptor instead.
func (*GroupConfig) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{4}
}

func (x *GroupConfig) GetLevels() []bool {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *GroupConfig) GetViewType() int32 {
	if x != nil {
		return x.ViewType
	}
	return 0
}

func (x *GroupConfig) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

func (x *GroupConfig) GetAutoFreezeDays() int32 {
	if x != nil {
		return x.AutoFreezeDays
	}
	return 0
}

type GroupSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateAt      int64                  `protobuf:"varint,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,4,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	OverAt        int64                  `protobuf:"varint,5,opt,name=over_at,json=overAt,proto3" json:"over_at,omitempty"`
	Config        *GroupConfig           `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	Permission    *PermissionEnvelope    `protobuf:"bytes,7,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSummary) Reset() {
	*x = GroupSummary{}
	mi := &file_whisperingtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSummary) ProtoMessage() {}

func (x *GroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSummary.ProtoReflect.Descriptor instead.
func (*GroupSummary) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{5}
}

func (x *GroupSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupSummary) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GroupSummary) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *GroupSummary) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *GroupSummary) GetOverAt() int64 {
	if x != nil {
		return x.OverAt
	}
	return 0
}

func (x *GroupSummary) GetConfig() *GroupConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GroupSummary) GetPermission() *PermissionEnvelope {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DocSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateAt      int64                  `protobuf:"varint,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,6,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Permission    *PermissionEnvelope    `protobuf:"bytes,7,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocSummary) Reset() {
	*x = DocSummary{}
	mi := &file_whisperingtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocSummary) ProtoMessage() {}

func (x *DocSummary) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocSummary.ProtoReflect.Descriptor instead.
func (*DocSummary) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{6}
}

func (x *DocSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocSummary) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocSummary) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *DocSummary) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *DocSummary) GetPermission() *PermissionEnvelope {
	if x != nil {
		return x.Permission
	}
	return nil
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         []byte                 `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Rich          []byte                 `protobuf:"bytes,2,opt,name=rich,proto3,oneof" json:"rich,omitempty"`
	Level         []byte                 `protobuf:"bytes,3,opt,name=level,proto3,oneof" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_whisperingtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{7}
}

func (x *Content) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Content) GetRich() []byte {
	if x != nil {
		return x.Rich
	}
	return nil
}

func (x *Content) GetLevel() []byte {
	if x != nil {
		return x.Level
	}
	return nil
}

type DocDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateAt      int64                  `protobuf:"varint,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,7,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Permission    *PermissionEnvelope    `protobuf:"bytes,8,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocDetail) Reset() {
	*x = DocDetail{}
	mi := &file_whisperingtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocDetail) ProtoMessage() {}

func (x *DocDetail) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocDetail.ProtoReflect.Descriptor instead.
func (*DocDetail) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{8}
}

func (x *DocDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocDetail) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocDetail) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *DocDetail) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

func (x *DocDetail) GetPermission() *PermissionEnvelope {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GroupDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *GroupConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Docs          []*DocDetail           `protobuf:"bytes,4,rep,name=docs,proto3" json:"docs,omitempty"`
	Permission    *PermissionEnvelope    `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDetail) Reset() {
	*x = GroupDetail{}
	mi := &file_whisperingtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetail) ProtoMessage() {}

func (x *GroupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetail.ProtoReflect.Descriptor instead.
func (*GroupDetail) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{9}
}

func (x *GroupDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupDetail) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GroupDetail) GetConfig() *GroupConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GroupDetail) GetDocs() []*DocDetail {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *GroupDetail) GetPermission() *PermissionEnvelope {
	if x != nil {
		return x.Permission
	}
	return nil
}

type ThemeDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Groups        []*GroupDetail         `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Permission    *PermissionEnvelope    `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeDetail) Reset() {
	*x = ThemeDetail{}
	mi := &file_whisperingtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeDetail) ProtoMessage() {}

func (x *ThemeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeDetail.ProtoReflect.Descriptor instead.
func (*ThemeDetail) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{10}
}

func (x *ThemeDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThemeDetail) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ThemeDetail) GetGroups() []*GroupDetail {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ThemeDetail) GetPermission() *PermissionEnvelope {
	if x != nil {
		return x.Permission
	}
	return nil
}

// Theme service
type ListThemesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeDocs   bool                   `protobuf:"varint,1,opt,name=include_docs,json=includeDocs,proto3" json:"include_docs,omitempty"`       // if true, include doc list per group (summary)
	IncludeDetail bool                   `protobuf:"varint,2,opt,name=include_detail,json=includeDetail,proto3" json:"include_detail,omitempty"` // if true, include full doc detail per group
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThemesRequest) Reset() {
	*x = ListThemesRequest{}
	mi := &file_whisperingtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThemesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThemesRequest) ProtoMessage() {}

func (x *ListThemesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThemesRequest.ProtoReflect.Descriptor instead.
func (*ListThemesRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{11}
}

func (x *ListThemesRequest) GetIncludeDocs() bool {
	if x != nil {
		return x.IncludeDocs
	}
	return false
}

func (x *ListThemesRequest) GetIncludeDetail() bool {
	if x != nil {
		return x.IncludeDetail
	}
	return false
}

type ListThemesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Themes        []*ThemeDetail         `protobuf:"bytes,3,rep,name=themes,proto3" json:"themes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThemesResponse) Reset() {
	*x = ListThemesResponse{}
	mi := &file_whisperingtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThemesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThemesResponse) ProtoMessage() {}

func (x *ListThemesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThemesResponse.ProtoReflect.Descriptor instead.
func (*ListThemesResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{12}
}

func (x *ListThemesResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *ListThemesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListThemesResponse) GetThemes() []*ThemeDetail {
	if x != nil {
		return x.Themes
	}
	return nil
}

type CreateThemeRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     []byte                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DefaultGroupName         []byte                 `protobuf:"bytes,2,opt,name=default_group_name,json=defaultGroupName,proto3" json:"default_group_name,omitempty"`
	EncryptedKey             []byte                 `protobuf:"bytes,3,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	DefaultGroupEncryptedKey []byte                 `protobuf:"bytes,4,opt,name=default_group_encrypted_key,json=defaultGroupEncryptedKey,proto3" json:"default_group_encrypted_key,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateThemeRequest) Reset() {
	*x = CreateThemeRequest{}
	mi := &file_whisperingtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThemeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThemeRequest) ProtoMessage() {}

func (x *CreateThemeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThemeRequest.ProtoReflect.Descriptor instead.
func (*CreateThemeRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{13}
}

func (x *CreateThemeRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CreateThemeRequest) GetDefaultGroupName() []byte {
	if x != nil {
		return x.DefaultGroupName
	}
	return nil
}

func (x *CreateThemeRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

func (x *CreateThemeRequest) GetDefaultGroupEncryptedKey() []byte {
	if x != nil {
		return x.DefaultGroupEncryptedKey
	}
	return nil
}

type CreateThemeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThemeResponse) Reset() {
	*x = CreateThemeResponse{}
	mi := &file_whisperingtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThemeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThemeResponse) ProtoMessage() {}

func (x *CreateThemeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThemeResponse.ProtoReflect.Descriptor instead.
func (*CreateThemeResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{14}
}

func (x *CreateThemeResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *CreateThemeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateThemeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateThemeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EncryptedKey  []byte                 `protobuf:"bytes,3,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateThemeRequest) Reset() {
	*x = UpdateThemeRequest{}
	mi := &file_whisperingtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThemeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThemeRequest) ProtoMessage() {}

func (x *UpdateThemeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThemeRequest.ProtoReflect.Descriptor instead.
func (*UpdateThemeRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateThemeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateThemeRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateThemeRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type DeleteThemeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThemeRequest) Reset() {
	*x = DeleteThemeRequest{}
	mi := &file_whisperingtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThemeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThemeRequest) ProtoMessage() {}

func (x *DeleteThemeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThemeRequest.ProtoReflect.Descriptor instead.
func (*DeleteThemeRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteThemeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExportAllConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAllConfigRequest) Reset() {
	*x = ExportAllConfigRequest{}
	mi := &file_whisperingtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAllConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAllConfigRequest) ProtoMessage() {}

func (x *ExportAllConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAllConfigRequest.ProtoReflect.Descriptor instead.
func (*ExportAllConfigRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{17}
}

// Group service
type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThemeId       string                 `protobuf:"bytes,1,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_whisperingtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{18}
}

func (x *ListGroupsRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Groups        []*GroupSummary        `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_whisperingtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{19}
}

func (x *ListGroupsResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *ListGroupsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListGroupsResponse) GetGroups() []*GroupSummary {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThemeId       string                 `protobuf:"bytes,1,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	IncludeDocs   bool                   `protobuf:"varint,3,opt,name=include_docs,json=includeDocs,proto3" json:"include_docs,omitempty"`
	IncludeDetail bool                   `protobuf:"varint,4,opt,name=include_detail,json=includeDetail,proto3" json:"include_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_whisperingtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{20}
}

func (x *GetGroupRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupRequest) GetIncludeDocs() bool {
	if x != nil {
		return x.IncludeDocs
	}
	return false
}

func (x *GetGroupRequest) GetIncludeDetail() bool {
	if x != nil {
		return x.IncludeDetail
	}
	return false
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Group         *GroupDetail           `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_whisperingtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{21}
}

func (x *GetGroupResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *GetGroupResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGroupResponse) GetGroup() *GroupDetail {
	if x != nil {
		return x.Group
	}
	return nil
}

type CreateGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThemeId        string                 `protobuf:"bytes,1,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	Name           []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AutoFreezeDays int32                  `protobuf:"varint,3,opt,name=auto_freeze_days,json=autoFreezeDays,proto3" json:"auto_freeze_days,omitempty"`
	EncryptedKey   []byte                 `protobuf:"bytes,4,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_whisperingtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{22}
}

func (x *CreateGroupRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *CreateGroupRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CreateGroupRequest) GetAutoFreezeDays() int32 {
	if x != nil {
		return x.AutoFreezeDays
	}
	return 0
}

func (x *CreateGroupRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_whisperingtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{23}
}

func (x *CreateGroupResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *CreateGroupResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateGroupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThemeId       string                 `protobuf:"bytes,1,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          []byte                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Config        *GroupConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	OverAt        int64                  `protobuf:"varint,5,opt,name=over_at,json=overAt,proto3" json:"over_at,omitempty"`
	EncryptedKey  []byte                 `protobuf:"bytes,6,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_whisperingtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateGroupRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateGroupRequest) GetConfig() *GroupConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateGroupRequest) GetOverAt() int64 {
	if x != nil {
		return x.OverAt
	}
	return 0
}

func (x *UpdateGroupRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThemeId       string                 `protobuf:"bytes,1,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_whisperingtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteGroupRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *DeleteGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ExportGroupConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThemeId       string                 `protobuf:"bytes,1,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportGroupConfigRequest) Reset() {
	*x = ExportGroupConfigRequest{}
	mi := &file_whisperingtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportGroupConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportGroupConfigRequest) ProtoMessage() {}

func (x *ExportGroupConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportGroupConfigRequest.ProtoReflect.Descriptor instead.
func (*ExportGroupConfigRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{26}
}

func (x *ExportGroupConfigRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *ExportGroupConfigRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ImportGroupConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportGroupConfigResponse) Reset() {
	*x = ImportGroupConfigResponse{}
	mi := &file_whisperingtime_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportGroupConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportGroupConfigResponse) ProtoMessage() {}

func (x *ImportGroupConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportGroupConfigResponse.ProtoReflect.Descriptor instead.
func (*ImportGroupConfigResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{27}
}

func (x *ImportGroupConfigResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *ImportGroupConfigResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Doc service
type ListDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocsRequest) Reset() {
	*x = ListDocsRequest{}
	mi := &file_whisperingtime_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocsRequest) ProtoMessage() {}

func (x *ListDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocsRequest.ProtoReflect.Descriptor instead.
func (*ListDocsRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{28}
}

func (x *ListDocsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListDocsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListDocsRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type ListDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Docs          []*DocSummary          `protobuf:"bytes,3,rep,name=docs,proto3" json:"docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocsResponse) Reset() {
	*x = ListDocsResponse{}
	mi := &file_whisperingtime_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocsResponse) ProtoMessage() {}

func (x *ListDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocsResponse.ProtoReflect.Descriptor instead.
func (*ListDocsResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{29}
}

func (x *ListDocsResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *ListDocsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListDocsResponse) GetDocs() []*DocSummary {
	if x != nil {
		return x.Docs
	}
	return nil
}

type CreateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Content       *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateAt      int64                  `protobuf:"varint,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	EncryptedKey  []byte                 `protobuf:"bytes,7,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocRequest) Reset() {
	*x = CreateDocRequest{}
	mi := &file_whisperingtime_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocRequest) ProtoMessage() {}

func (x *CreateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocRequest.ProtoReflect.Descriptor instead.
func (*CreateDocRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{30}
}

func (x *CreateDocRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateDocRequest) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CreateDocRequest) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *CreateDocRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type CreateDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocResponse) Reset() {
	*x = CreateDocResponse{}
	mi := &file_whisperingtime_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocResponse) ProtoMessage() {}

func (x *CreateDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocResponse.ProtoReflect.Descriptor instead.
func (*CreateDocResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{31}
}

func (x *CreateDocResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *CreateDocResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateDocResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Content       *Content               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateAt      int64                  `protobuf:"varint,7,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	EncryptedKey  []byte                 `protobuf:"bytes,8,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocRequest) Reset() {
	*x = UpdateDocRequest{}
	mi := &file_whisperingtime_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocRequest) ProtoMessage() {}

func (x *UpdateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateDocRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateDocRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *UpdateDocRequest) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateDocRequest) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *UpdateDocRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type DeleteDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocRequest) Reset() {
	*x = DeleteDocRequest{}
	mi := &file_whisperingtime_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocRequest) ProtoMessage() {}

func (x *DeleteDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteDocRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DeleteDocRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

// Image service
type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_whisperingtime_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{34}
}

func (x *UploadImageResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *UploadImageResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadImageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageRequest) Reset() {
	*x = DeleteImageRequest{}
	mi := &file_whisperingtime_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageRequest) ProtoMessage() {}

func (x *DeleteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImageUploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uid
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`                   // image/png or image/jpeg
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUploadChunk) Reset() {
	*x = ImageUploadChunk{}
	mi := &file_whisperingtime_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadChunk) ProtoMessage() {}

func (x *ImageUploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadChunk.ProtoReflect.Descriptor instead.
func (*ImageUploadChunk) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{36}
}

func (x *ImageUploadChunk) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImageUploadChunk) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ImageUploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Background job service
type BackgroundJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	JobType       string                 `protobuf:"bytes,3,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     string                 `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	RetryCount    int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ResultJson    string                 `protobuf:"bytes,10,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	ErrorJson     string                 `protobuf:"bytes,11,opt,name=error_json,json=errorJson,proto3" json:"error_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundJob) Reset() {
	*x = BackgroundJob{}
	mi := &file_whisperingtime_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundJob) ProtoMessage() {}

func (x *BackgroundJob) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundJob.ProtoReflect.Descriptor instead.
func (*BackgroundJob) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{37}
}

func (x *BackgroundJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackgroundJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackgroundJob) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *BackgroundJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BackgroundJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BackgroundJob) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *BackgroundJob) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *BackgroundJob) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *BackgroundJob) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *BackgroundJob) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *BackgroundJob) GetErrorJson() string {
	if x != nil {
		return x.ErrorJson
	}
	return ""
}

type ListBackgroundJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackgroundJobsRequest) Reset() {
	*x = ListBackgroundJobsRequest{}
	mi := &file_whisperingtime_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackgroundJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackgroundJobsRequest) ProtoMessage() {}

func (x *ListBackgroundJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackgroundJobsRequest.ProtoReflect.Descriptor instead.
func (*ListBackgroundJobsRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{38}
}

type ListBackgroundJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Jobs          []*BackgroundJob       `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackgroundJobsResponse) Reset() {
	*x = ListBackgroundJobsResponse{}
	mi := &file_whisperingtime_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackgroundJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackgroundJobsResponse) ProtoMessage() {}

func (x *ListBackgroundJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackgroundJobsResponse.ProtoReflect.Descriptor instead.
func (*ListBackgroundJobsResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{39}
}

func (x *ListBackgroundJobsResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *ListBackgroundJobsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListBackgroundJobsResponse) GetJobs() []*BackgroundJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type GetBackgroundJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackgroundJobRequest) Reset() {
	*x = GetBackgroundJobRequest{}
	mi := &file_whisperingtime_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackgroundJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackgroundJobRequest) ProtoMessage() {}

func (x *GetBackgroundJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackgroundJobRequest.ProtoReflect.Descriptor instead.
func (*GetBackgroundJobRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{40}
}

func (x *GetBackgroundJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBackgroundJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackgroundJobRequest) Reset() {
	*x = DeleteBackgroundJobRequest{}
	mi := &file_whisperingtime_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackgroundJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackgroundJobRequest) ProtoMessage() {}

func (x *DeleteBackgroundJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackgroundJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackgroundJobRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{41}
}

func (x *DeleteBackgroundJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadBackgroundJobFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBackgroundJobFileRequest) Reset() {
	*x = DownloadBackgroundJobFileRequest{}
	mi := &file_whisperingtime_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBackgroundJobFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBackgroundJobFileRequest) ProtoMessage() {}

func (x *DownloadBackgroundJobFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBackgroundJobFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadBackgroundJobFileRequest) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{42}
}

func (x *DownloadBackgroundJobFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadBackgroundJobFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           int32                  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBackgroundJobFileResponse) Reset() {
	*x = DownloadBackgroundJobFileResponse{}
	mi := &file_whisperingtime_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBackgroundJobFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBackgroundJobFileResponse) ProtoMessage() {}

func (x *DownloadBackgroundJobFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBackgroundJobFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadBackgroundJobFileResponse) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{43}
}

func (x *DownloadBackgroundJobFileResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *DownloadBackgroundJobFileResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DownloadBackgroundJobFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadBackgroundJobFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Shared chunk message for client streaming uploads
type BytesChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesChunk) Reset() {
	*x = BytesChunk{}
	mi := &file_whisperingtime_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesChunk) ProtoMessage() {}

func (x *BytesChunk) ProtoReflect() protoreflect.Message {
	mi := &file_whisperingtime_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesChunk.ProtoReflect.Descriptor instead.
func (*BytesChunk) Descriptor() ([]byte, []int) {
	return file_whisperingtime_proto_rawDescGZIP(), []int{44}
}

func (x *BytesChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_whisperingtime_proto protoreflect.FileDescriptor

const file_whisperingtime_proto_rawDesc = "" +
	"\n" +
	"\x14whisperingtime.proto\x12\x0ewhisperingtime\"3\n" +
	"\rBasicResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\a\n" +
	"\x05Empty\"2\n" +
	"\fThemeSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\"M\n" +
	"\x12PermissionEnvelope\x12#\n" +
	"\rencrypted_key\x18\x01 \x01(\fR\fencryptedKey\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x89\x01\n" +
	"\vGroupConfig\x12\x16\n" +
	"\x06levels\x18\x03 \x03(\bR\x06levels\x12\x1b\n" +
	"\tview_type\x18\x04 \x01(\x05R\bviewType\x12\x1b\n" +
	"\tsort_type\x18\x05 \x01(\x05R\bsortType\x12(\n" +
	"\x10auto_freeze_days\x18\x06 \x01(\x05R\x0eautoFreezeDays\"\xfe\x01\n" +
	"\fGroupSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x12\x1b\n" +
	"\tcreate_at\x18\x03 \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\x04 \x01(\x03R\bupdateAt\x12\x17\n" +
	"\aover_at\x18\x05 \x01(\x03R\x06overAt\x123\n" +
	"\x06config\x18\x06 \x01(\v2\x1b.whisperingtime.GroupConfigR\x06config\x12B\n" +
	"\n" +
	"permission\x18\a \x01(\v2\".whisperingtime.PermissionEnvelopeR\n" +
	"permission\"\xd3\x01\n" +
	"\n" +
	"DocSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\acontent\x18\x02 \x01(\v2\x17.whisperingtime.ContentR\acontent\x12\x1b\n" +
	"\tcreate_at\x18\x05 \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\x06 \x01(\x03R\bupdateAt\x12B\n" +
	"\n" +
	"permission\x18\a \x01(\v2\".whisperingtime.PermissionEnvelopeR\n" +
	"permissionJ\x04\b\x04\x10\x05\"u\n" +
	"\aContent\x12\x19\n" +
	"\x05title\x18\x01 \x01(\fH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04rich\x18\x02 \x01(\fH\x01R\x04rich\x88\x01\x01\x12\x19\n" +
	"\x05level\x18\x03 \x01(\fH\x02R\x05level\x88\x01\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_richB\b\n" +
	"\x06_level\"\xd2\x01\n" +
	"\tDocDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\acontent\x18\x02 \x01(\v2\x17.whisperingtime.ContentR\acontent\x12\x1b\n" +
	"\tcreate_at\x18\x06 \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\a \x01(\x03R\bupdateAt\x12B\n" +
	"\n" +
	"permission\x18\b \x01(\v2\".whisperingtime.PermissionEnvelopeR\n" +
	"permissionJ\x04\b\x05\x10\x06\"\xd9\x01\n" +
	"\vGroupDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x123\n" +
	"\x06config\x18\x03 \x01(\v2\x1b.whisperingtime.GroupConfigR\x06config\x12-\n" +
	"\x04docs\x18\x04 \x03(\v2\x19.whisperingtime.DocDetailR\x04docs\x12B\n" +
	"\n" +
	"permission\x18\x05 \x01(\v2\".whisperingtime.PermissionEnvelopeR\n" +
	"permission\"\xaa\x01\n" +
	"\vThemeDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x123\n" +
	"\x06groups\x18\x03 \x03(\v2\x1b.whisperingtime.GroupDetailR\x06groups\x12B\n" +
	"\n" +
	"permission\x18\x04 \x01(\v2\".whisperingtime.PermissionEnvelopeR\n" +
	"permission\"]\n" +
	"\x11ListThemesRequest\x12!\n" +
	"\finclude_docs\x18\x01 \x01(\bR\vincludeDocs\x12%\n" +
	"\x0einclude_detail\x18\x02 \x01(\bR\rincludeDetail\"m\n" +
	"\x12ListThemesResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x123\n" +
	"\x06themes\x18\x03 \x03(\v2\x1b.whisperingtime.ThemeDetailR\x06themes\"\xba\x01\n" +
	"\x12CreateThemeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12,\n" +
	"\x12default_group_name\x18\x02 \x01(\fR\x10defaultGroupName\x12#\n" +
	"\rencrypted_key\x18\x03 \x01(\fR\fencryptedKey\x12=\n" +
	"\x1bdefault_group_encrypted_key\x18\x04 \x01(\fR\x18defaultGroupEncryptedKey\"I\n" +
	"\x13CreateThemeResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"]\n" +
	"\x12UpdateThemeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x12#\n" +
	"\rencrypted_key\x18\x03 \x01(\fR\fencryptedKey\"$\n" +
	"\x12DeleteThemeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ExportAllConfigRequest\".\n" +
	"\x11ListGroupsRequest\x12\x19\n" +
	"\btheme_id\x18\x01 \x01(\tR\athemeId\"n\n" +
	"\x12ListGroupsResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x124\n" +
	"\x06groups\x18\x03 \x03(\v2\x1c.whisperingtime.GroupSummaryR\x06groups\"\x91\x01\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\btheme_id\x18\x01 \x01(\tR\athemeId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12!\n" +
	"\finclude_docs\x18\x03 \x01(\bR\vincludeDocs\x12%\n" +
	"\x0einclude_detail\x18\x04 \x01(\bR\rincludeDetail\"i\n" +
	"\x10GetGroupResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x121\n" +
	"\x05group\x18\x03 \x01(\v2\x1b.whisperingtime.GroupDetailR\x05group\"\x92\x01\n" +
	"\x12CreateGroupRequest\x12\x19\n" +
	"\btheme_id\x18\x01 \x01(\tR\athemeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x12(\n" +
	"\x10auto_freeze_days\x18\x03 \x01(\x05R\x0eautoFreezeDays\x12#\n" +
	"\rencrypted_key\x18\x04 \x01(\fR\fencryptedKey\"I\n" +
	"\x13CreateGroupResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xd1\x01\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\btheme_id\x18\x01 \x01(\tR\athemeId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\fR\x04name\x123\n" +
	"\x06config\x18\x04 \x01(\v2\x1b.whisperingtime.GroupConfigR\x06config\x12\x17\n" +
	"\aover_at\x18\x05 \x01(\x03R\x06overAt\x12#\n" +
	"\rencrypted_key\x18\x06 \x01(\fR\fencryptedKey\"J\n" +
	"\x12DeleteGroupRequest\x12\x19\n" +
	"\btheme_id\x18\x01 \x01(\tR\athemeId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"P\n" +
	"\x18ExportGroupConfigRequest\x12\x19\n" +
	"\btheme_id\x18\x01 \x01(\tR\athemeId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"?\n" +
	"\x19ImportGroupConfigResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"V\n" +
	"\x0fListDocsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"f\n" +
	"\x10ListDocsResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\x04docs\x18\x03 \x03(\v2\x1a.whisperingtime.DocSummaryR\x04docs\"\xa8\x01\n" +
	"\x10CreateDocRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x121\n" +
	"\acontent\x18\x02 \x01(\v2\x17.whisperingtime.ContentR\acontent\x12\x1b\n" +
	"\tcreate_at\x18\x06 \x01(\x03R\bcreateAt\x12#\n" +
	"\rencrypted_key\x18\a \x01(\fR\fencryptedKeyJ\x04\b\x05\x10\x06\"G\n" +
	"\x11CreateDocResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xbf\x01\n" +
	"\x10UpdateDocRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x121\n" +
	"\acontent\x18\x03 \x01(\v2\x17.whisperingtime.ContentR\acontent\x12\x1b\n" +
	"\tcreate_at\x18\a \x01(\x03R\bcreateAt\x12#\n" +
	"\rencrypted_key\x18\b \x01(\fR\fencryptedKeyJ\x04\b\x06\x10\a\"D\n" +
	"\x10DeleteDocRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"_\n" +
	"\x13UploadImageResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"(\n" +
	"\x12DeleteImageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"S\n" +
	"\x10ImageUploadChunk\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xc4\x02\n" +
	"\rBackgroundJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bjob_type\x18\x03 \x01(\tR\ajobType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\tR\vcompletedAt\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vresult_json\x18\n" +
	" \x01(\tR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"error_json\x18\v \x01(\tR\terrorJson\"\x1b\n" +
	"\x19ListBackgroundJobsRequest\"s\n" +
	"\x1aListBackgroundJobsResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x121\n" +
	"\x04jobs\x18\x03 \x03(\v2\x1d.whisperingtime.BackgroundJobR\x04jobs\")\n" +
	"\x17GetBackgroundJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x1aDeleteBackgroundJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	" DownloadBackgroundJobFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"!DownloadBackgroundJobFileResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\x05R\x03err\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\" \n" +
	"\n" +
	"BytesChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xb9\x03\n" +
	"\fThemeService\x12S\n" +
	"\n" +
	"ListThemes\x12!.whisperingtime.ListThemesRequest\x1a\".whisperingtime.ListThemesResponse\x12V\n" +
	"\vCreateTheme\x12\".whisperingtime.CreateThemeRequest\x1a#.whisperingtime.CreateThemeResponse\x12P\n" +
	"\vUpdateTheme\x12\".whisperingtime.UpdateThemeRequest\x1a\x1d.whisperingtime.BasicResponse\x12P\n" +
	"\vDeleteTheme\x12\".whisperingtime.DeleteThemeRequest\x1a\x1d.whisperingtime.BasicResponse\x12X\n" +
	"\x0fExportAllConfig\x12&.whisperingtime.ExportAllConfigRequest\x1a\x1d.whisperingtime.BasicResponse2\xea\x04\n" +
	"\fGroupService\x12S\n" +
	"\n" +
	"ListGroups\x12!.whisperingtime.ListGroupsRequest\x1a\".whisperingtime.ListGroupsResponse\x12M\n" +
	"\bGetGroup\x12\x1f.whisperingtime.GetGroupRequest\x1a .whisperingtime.GetGroupResponse\x12V\n" +
	"\vCreateGroup\x12\".whisperingtime.CreateGroupRequest\x1a#.whisperingtime.CreateGroupResponse\x12P\n" +
	"\vUpdateGroup\x12\".whisperingtime.UpdateGroupRequest\x1a\x1d.whisperingtime.BasicResponse\x12P\n" +
	"\vDeleteGroup\x12\".whisperingtime.DeleteGroupRequest\x1a\x1d.whisperingtime.BasicResponse\x12\\\n" +
	"\x11ExportGroupConfig\x12(.whisperingtime.ExportGroupConfigRequest\x1a\x1d.whisperingtime.BasicResponse\x12\\\n" +
	"\x11ImportGroupConfig\x12\x1a.whisperingtime.BytesChunk\x1a).whisperingtime.ImportGroupConfigResponse(\x012\xc9\x02\n" +
	"\n" +
	"DocService\x12M\n" +
	"\bListDocs\x12\x1f.whisperingtime.ListDocsRequest\x1a .whisperingtime.ListDocsResponse\x12P\n" +
	"\tCreateDoc\x12 .whisperingtime.CreateDocRequest\x1a!.whisperingtime.CreateDocResponse\x12L\n" +
	"\tUpdateDoc\x12 .whisperingtime.UpdateDocRequest\x1a\x1d.whisperingtime.BasicResponse\x12L\n" +
	"\tDeleteDoc\x12 .whisperingtime.DeleteDocRequest\x1a\x1d.whisperingtime.BasicResponse2\xb8\x01\n" +
	"\fImageService\x12V\n" +
	"\vUploadImage\x12 .whisperingtime.ImageUploadChunk\x1a#.whisperingtime.UploadImageResponse(\x01\x12P\n" +
	"\vDeleteImage\x12\".whisperingtime.DeleteImageRequest\x1a\x1d.whisperingtime.BasicResponse2\x9b\x03\n" +
	"\x14BackgroundJobService\x12a\n" +
	"\bListJobs\x12).whisperingtime.ListBackgroundJobsRequest\x1a*.whisperingtime.ListBackgroundJobsResponse\x12P\n" +
	"\x06GetJob\x12'.whisperingtime.GetBackgroundJobRequest\x1a\x1d.whisperingtime.BackgroundJob\x12V\n" +
	"\tDeleteJob\x12*.whisperingtime.DeleteBackgroundJobRequest\x1a\x1d.whisperingtime.BasicResponse\x12v\n" +
	"\x0fDownloadJobFile\x120.whisperingtime.DownloadBackgroundJobFileRequest\x1a1.whisperingtime.DownloadBackgroundJobFileResponseBP\n" +
	"\x17dev.whisperingtime.grpcP\x01Z3github.com/tengfei-xy/whisperingtime/engine/grpc/pbb\x06proto3"

var (
	file_whisperingtime_proto_rawDescOnce sync.Once
	file_whisperingtime_proto_rawDescData []byte
)

func file_whisperingtime_proto_rawDescGZIP() []byte {
	file_whisperingtime_proto_rawDescOnce.Do(func() {
		file_whisperingtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whisperingtime_proto_rawDesc), len(file_whisperingtime_proto_rawDesc)))
	})
	return file_whisperingtime_proto_rawDescData
}

var file_whisperingtime_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_whisperingtime_proto_goTypes = []any{
	(*BasicResponse)(nil),                     // 0: whisperingtime.BasicResponse
	(*Empty)(nil),                             // 1: whisperingtime.Empty
	(*ThemeSummary)(nil),                      // 2: whisperingtime.ThemeSummary
	(*PermissionEnvelope)(nil),                // 3: whisperingtime.PermissionEnvelope
	(*GroupConfig)(nil),                       // 4: whisperingtime.GroupConfig
	(*GroupSummary)(nil),                      // 5: whisperingtime.GroupSummary
	(*DocSummary)(nil),                        // 6: whisperingtime.DocSummary
	(*Content)(nil),                           // 7: whisperingtime.Content
	(*DocDetail)(nil),                         // 8: whisperingtime.DocDetail
	(*GroupDetail)(nil),                       // 9: whisperingtime.GroupDetail
	(*ThemeDetail)(nil),                       // 10: whisperingtime.ThemeDetail
	(*ListThemesRequest)(nil),                 // 11: whisperingtime.ListThemesRequest
	(*ListThemesResponse)(nil),                // 12: whisperingtime.ListThemesResponse
	(*CreateThemeRequest)(nil),                // 13: whisperingtime.CreateThemeRequest
	(*CreateThemeResponse)(nil),               // 14: whisperingtime.CreateThemeResponse
	(*UpdateThemeRequest)(nil),                // 15: whisperingtime.UpdateThemeRequest
	(*DeleteThemeRequest)(nil),                // 16: whisperingtime.DeleteThemeRequest
	(*ExportAllConfigRequest)(nil),            // 17: whisperingtime.ExportAllConfigRequest
	(*ListGroupsRequest)(nil),                 // 18: whisperingtime.ListGroupsRequest
	(*ListGroupsResponse)(nil),                // 19: whisperingtime.ListGroupsResponse
	(*GetGroupRequest)(nil),                   // 20: whisperingtime.GetGroupRequest
	(*GetGroupResponse)(nil),                  // 21: whisperingtime.GetGroupResponse
	(*CreateGroupRequest)(nil),                // 22: whisperingtime.CreateGroupRequest
	(*CreateGroupResponse)(nil),               // 23: whisperingtime.CreateGroupResponse
	(*UpdateGroupRequest)(nil),                // 24: whisperingtime.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),                // 25: whisperingtime.DeleteGroupRequest
	(*ExportGroupConfigRequest)(nil),          // 26: whisperingtime.ExportGroupConfigRequest
	(*ImportGroupConfigResponse)(nil),         // 27: whisperingtime.ImportGroupConfigResponse
	(*ListDocsRequest)(nil),                   // 28: whisperingtime.ListDocsRequest
	(*ListDocsResponse)(nil),                  // 29: whisperingtime.ListDocsResponse
	(*CreateDocRequest)(nil),                  // 30: whisperingtime.CreateDocRequest
	(*CreateDocResponse)(nil),                 // 31: whisperingtime.CreateDocResponse
	(*UpdateDocRequest)(nil),                  // 32: whisperingtime.UpdateDocRequest
	(*DeleteDocRequest)(nil),                  // 33: whisperingtime.DeleteDocRequest
	(*UploadImageResponse)(nil),               // 34: whisperingtime.UploadImageResponse
	(*DeleteImageRequest)(nil),                // 35: whisperingtime.DeleteImageRequest
	(*ImageUploadChunk)(nil),                  // 36: whisperingtime.ImageUploadChunk
	(*BackgroundJob)(nil),                     // 37: whisperingtime.BackgroundJob
	(*ListBackgroundJobsRequest)(nil),         // 38: whisperingtime.ListBackgroundJobsRequest
	(*ListBackgroundJobsResponse)(nil),        // 39: whisperingtime.ListBackgroundJobsResponse
	(*GetBackgroundJobRequest)(nil),           // 40: whisperingtime.GetBackgroundJobRequest
	(*DeleteBackgroundJobRequest)(nil),        // 41: whisperingtime.DeleteBackgroundJobRequest
	(*DownloadBackgroundJobFileRequest)(nil),  // 42: whisperingtime.DownloadBackgroundJobFileRequest
	(*DownloadBackgroundJobFileResponse)(nil), // 43: whisperingtime.DownloadBackgroundJobFileResponse
	(*BytesChunk)(nil),                        // 44: whisperingtime.BytesChunk
}
var file_whisperingtime_proto_depIdxs = []int32{
	4,  // 0: whisperingtime.GroupSummary.config:type_name -> whisperingtime.GroupConfig
	3,  // 1: whisperingtime.GroupSummary.permission:type_name -> whisperingtime.PermissionEnvelope
	7,  // 2: whisperingtime.DocSummary.content:type_name -> whisperingtime.Content
	3,  // 3: whisperingtime.DocSummary.permission:type_name -> whisperingtime.PermissionEnvelope
	7,  // 4: whisperingtime.DocDetail.content:type_name -> whisperingtime.Content
	3,  // 5: whisperingtime.DocDetail.permission:type_name -> whisperingtime.PermissionEnvelope
	4,  // 6: whisperingtime.GroupDetail.config:type_name -> whisperingtime.GroupConfig
	8,  // 7: whisperingtime.GroupDetail.docs:type_name -> whisperingtime.DocDetail
	3,  // 8: whisperingtime.GroupDetail.permission:type_name -> whisperingtime.PermissionEnvelope
	9,  // 9: whisperingtime.ThemeDetail.groups:type_name -> whisperingtime.GroupDetail
	3,  // 10: whisperingtime.ThemeDetail.permission:type_name -> whisperingtime.PermissionEnvelope
	10, // 11: whisperingtime.ListThemesResponse.themes:type_name -> whisperingtime.ThemeDetail
	5,  // 12: whisperingtime.ListGroupsResponse.groups:type_name -> whisperingtime.GroupSummary
	9,  // 13: whisperingtime.GetGroupResponse.group:type_name -> whisperingtime.GroupDetail
	4,  // 14: whisperingtime.UpdateGroupRequest.config:type_name -> whisperingtime.GroupConfig
	6,  // 15: whisperingtime.ListDocsResponse.docs:type_name -> whisperingtime.DocSummary
	7,  // 16: whisperingtime.CreateDocRequest.content:type_name -> whisperingtime.Content
	7,  // 17: whisperingtime.UpdateDocRequest.content:type_name -> whisperingtime.Content
	37, // 18: whisperingtime.ListBackgroundJobsResponse.jobs:type_name -> whisperingtime.BackgroundJob
	11, // 19: whisperingtime.ThemeService.ListThemes:input_type -> whisperingtime.ListThemesRequest
	13, // 20: whisperingtime.ThemeService.CreateTheme:input_type -> whisperingtime.CreateThemeRequest
	15, // 21: whisperingtime.ThemeService.UpdateTheme:input_type -> whisperingtime.UpdateThemeRequest
	16, // 22: whisperingtime.ThemeService.DeleteTheme:input_type -> whisperingtime.DeleteThemeRequest
	17, // 23: whisperingtime.ThemeService.ExportAllConfig:input_type -> whisperingtime.ExportAllConfigRequest
	18, // 24: whisperingtime.GroupService.ListGroups:input_type -> whisperingtime.ListGroupsRequest
	20, // 25: whisperingtime.GroupService.GetGroup:input_type -> whisperingtime.GetGroupRequest
	22, // 26: whisperingtime.GroupService.CreateGroup:input_type -> whisperingtime.CreateGroupRequest
	24, // 27: whisperingtime.GroupService.UpdateGroup:input_type -> whisperingtime.UpdateGroupRequest
	25, // 28: whisperingtime.GroupService.DeleteGroup:input_type -> whisperingtime.DeleteGroupRequest
	26, // 29: whisperingtime.GroupService.ExportGroupConfig:input_type -> whisperingtime.ExportGroupConfigRequest
	44, // 30: whisperingtime.GroupService.ImportGroupConfig:input_type -> whisperingtime.BytesChunk
	28, // 31: whisperingtime.DocService.ListDocs:input_type -> whisperingtime.ListDocsRequest
	30, // 32: whisperingtime.DocService.CreateDoc:input_type -> whisperingtime.CreateDocRequest
	32, // 33: whisperingtime.DocService.UpdateDoc:input_type -> whisperingtime.UpdateDocRequest
	33, // 34: whisperingtime.DocService.DeleteDoc:input_type -> whisperingtime.DeleteDocRequest
	36, // 35: whisperingtime.ImageService.UploadImage:input_type -> whisperingtime.ImageUploadChunk
	35, // 36: whisperingtime.ImageService.DeleteImage:input_type -> whisperingtime.DeleteImageRequest
	38, // 37: whisperingtime.BackgroundJobService.ListJobs:input_type -> whisperingtime.ListBackgroundJobsRequest
	40, // 38: whisperingtime.BackgroundJobService.GetJob:input_type -> whisperingtime.GetBackgroundJobRequest
	41, // 39: whisperingtime.BackgroundJobService.DeleteJob:input_type -> whisperingtime.DeleteBackgroundJobRequest
	42, // 40: whisperingtime.BackgroundJobService.DownloadJobFile:input_type -> whisperingtime.DownloadBackgroundJobFileRequest
	12, // 41: whisperingtime.ThemeService.ListThemes:output_type -> whisperingtime.ListThemesResponse
	14, // 42: whisperingtime.ThemeService.CreateTheme:output_type -> whisperingtime.CreateThemeResponse
	0,  // 43: whisperingtime.ThemeService.UpdateTheme:output_type -> whisperingtime.BasicResponse
	0,  // 44: whisperingtime.ThemeService.DeleteTheme:output_type -> whisperingtime.BasicResponse
	0,  // 45: whisperingtime.ThemeService.ExportAllConfig:output_type -> whisperingtime.BasicResponse
	19, // 46: whisperingtime.GroupService.ListGroups:output_type -> whisperingtime.ListGroupsResponse
	21, // 47: whisperingtime.GroupService.GetGroup:output_type -> whisperingtime.GetGroupResponse
	23, // 48: whisperingtime.GroupService.CreateGroup:output_type -> whisperingtime.CreateGroupResponse
	0,  // 49: whisperingtime.GroupService.UpdateGroup:output_type -> whisperingtime.BasicResponse
	0,  // 50: whisperingtime.GroupService.DeleteGroup:output_type -> whisperingtime.BasicResponse
	0,  // 51: whisperingtime.GroupService.ExportGroupConfig:output_type -> whisperingtime.BasicResponse
	27, // 52: whisperingtime.GroupService.ImportGroupConfig:output_type -> whisperingtime.ImportGroupConfigResponse
	29, // 53: whisperingtime.DocService.ListDocs:output_type -> whisperingtime.ListDocsResponse
	31, // 54: whisperingtime.DocService.CreateDoc:output_type -> whisperingtime.CreateDocResponse
	0,  // 55: whisperingtime.DocService.UpdateDoc:output_type -> whisperingtime.BasicResponse
	0,  // 56: whisperingtime.DocService.DeleteDoc:output_type -> whisperingtime.BasicResponse
	34, // 57: whisperingtime.ImageService.UploadImage:output_type -> whisperingtime.UploadImageResponse
	0,  // 58: whisperingtime.ImageService.DeleteImage:output_type -> whisperingtime.BasicResponse
	39, // 59: whisperingtime.BackgroundJobService.ListJobs:output_type -> whisperingtime.ListBackgroundJobsResponse
	37, // 60: whisperingtime.BackgroundJobService.GetJob:output_type -> whisperingtime.BackgroundJob
	0,  // 61: whisperingtime.BackgroundJobService.DeleteJob:output_type -> whisperingtime.BasicResponse
	43, // 62: whisperingtime.BackgroundJobService.DownloadJobFile:output_type -> whisperingtime.DownloadBackgroundJobFileResponse
	41, // [41:63] is the sub-list for method output_type
	19, // [19:41] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_whisperingtime_proto_init() }
func file_whisperingtime_proto_init() {
	if File_whisperingtime_proto != nil {
		return
	}
	file_whisperingtime_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whisperingtime_proto_rawDesc), len(file_whisperingtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_whisperingtime_proto_goTypes,
		DependencyIndexes: file_whisperingtime_proto_depIdxs,
		MessageInfos:      file_whisperingtime_proto_msgTypes,
	}.Build()
	File_whisperingtime_proto = out.File
	file_whisperingtime_proto_goTypes = nil
	file_whisperingtime_proto_depIdxs = nil
}
