name: whispering_time
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.3.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  file_picker: ^9.0.2
  logger: ^2.5.0
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  image_picker: ^1.1.2
  gal: ^2.3.1
  path: ^1.9.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  device_info_plus: ^11.3.3
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon" # Android 图标文件名 (不包含扩展名)
  ios: true
  image_path: "assets/images/icon-512.png" # 你的主图标文件路径