name: whispering_time
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  file_picker: ^8.1.6
  logger: ^2.5.0
  flutter_quill: ^10.8.5
  flutter_quill_extensions: ^10.8.5
  image_picker: ^1.1.2
  gal: ^2.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true